version: '3'
services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  backend:
    build: ./  # Este es el directorio donde está tu Dockerfile para Spring Boot
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis  # Nombre del servicio Redis (esto es lo que Spring usará para conectarse)
      SPRING_REDIS_PORT: 6379   # Puerto donde Redis escucha
    depends_on:
      - postgres
      - redis  # Asegura que Redis se inicie antes que el backend
    networks:
      - backend_net

  redis:
    image: redis:alpine
    container_name: redis-compensaciones
    ports:
      - "6379:6379"
    networks:
      - backend_net

volumes:
  postgres_data:

networks:
  backend_net:
