  version: '3'
  services:
  
    postgres:
      image: postgres:15
      container_name: postgres-db
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - backend_net
  
    backend:
      build: ./
      container_name: spring-backend
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 1234
      depends_on:
        - postgres
      networks:
        - backend_net

  
  volumes:
    postgres_data:
  
  networks:
    backend_net:
