-- Tabla de bancos de destino
CREATE TABLE public.banco_destino (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	endpoint varchar(255) NULL,
	moneda varchar(255) NULL,
	pais varchar(255) NULL,
	CONSTRAINT banco_destino_pkey PRIMARY KEY (id)
);

-- Tabla principal de compensaciones
CREATE TABLE public.compensaciones (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ejecutado bool NOT NULL,
	fecha_registro timestamp(6) DEFAULT CURRENT_TIMESTAMP NULL,
	moneda_destino varchar(255) NULL,
	moneda_origen varchar(255) NULL,
	monto numeric(38, 2) NULL,
	tipo_cambio numeric(38, 2) NULL,
	monto_convertido numeric(38, 2) NULL,
	CONSTRAINT compensaciones_pkey PRIMARY KEY (id)
);
-- Tabla para paquetes que llegan a Bancolombia
CREATE TABLE public.bancolombia_paquetes (
	fecha_recepcion timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	estado varchar(255) NOT NULL,
	monto_total numeric(38, 2) DEFAULT 0 NOT NULL,
	id uuid NOT NULL,
	CONSTRAINT bancolombia_paquetes_pkey PRIMARY KEY (id)
);
-- Tabla con detalle de transacciones recibidas por Bancolombia
CREATE TABLE public.bancolombia_transacciones (
	id bigserial NOT NULL,
	monto numeric(38, 2) NOT NULL,
	moneda_origen varchar(255) NOT NULL,
	moneda_destino varchar(255) NOT NULL,
	tipo_cambio numeric(38, 2) NULL,
	ejecutado bool NULL,
	fecha_registro timestamp NULL,
	paquete uuid NULL,
	CONSTRAINT bancolombia_transacciones_pkey PRIMARY KEY (id)
);